// <auto-generated />
using EFPROJESİ4._07._2023.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFPROJESİ4._07._2023.Migrations
{
    [DbContext(typeof(YapilacakIslerDbContext))]
    [Migration("20230704090441_ilkolusum")]
    partial class ilkolusum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFPROJESİ4._07._2023.Entities.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("todoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Done = false,
                            Title = "Proje teklifini tamamla"
                        },
                        new
                        {
                            Id = 2,
                            Done = false,
                            Title = "Sunum slaytlarını hazırla"
                        },
                        new
                        {
                            Id = 3,
                            Done = true,
                            Title = "Kod değişikliklerini gözden geçir"
                        },
                        new
                        {
                            Id = 4,
                            Done = true,
                            Title = "Takip e-postalarını gönder"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
